version: '3.8'

services:
  react-local-dev:
    container_name: nextjs
    build:
      context: ./
      dockerfile: Dockerfile.local
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
